version: '3.8'

services:
  app:
    image: ozieblomichal/fastapi-template:latest
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/mydatabase

  db:
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: