name: Docker and Pytest Workflow

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker image
      run: docker build -t vitefast:latest .
    - name: Run Pytest in /src directory
      run: docker run --rm vitefast:latest /bin/sh -c "cd src && cd backend && poetry run python -m pytest ."


